### ISSUE TITLE
Not work USB port(keyboard/mouse) radxa-cm5-rpi-cm4-io-6_1_bookworm_kde_t3.output.img 

### ISSUE THREAD

**Issue by choihyunyong** [radxa-build/radxa-cm5-rpi-cm4-io-6_1#1]
Hello

I found [github](https://github.com/rockchip-linux/rkbin) and build loader.

And flash [radxa-cm5-rpi-cm4-io-6_1_bookworm 1](https://github.com/radxa-build/radxa-cm5-rpi-cm4-io-6_1/releases/tag/t3) but mouse/keyboard didn`t work on Rraspberry pi cm4 IO Board.

It seems like power isn’t being supplied to the USB port. :frowning:

**Comment by RadxaYuntian** [comment]
Thanks for your report. I have assigned this issue to our engineer to look at.

**Comment by Ken-Vamrs** [comment]
> Hello
> 
> I found [github](https://github.com/rockchip-linux/rkbin) and build loader.
> 
> And flash [radxa-cm5-rpi-cm4-io-6_1_bookworm 1](https://github.com/radxa-build/radxa-cm5-rpi-cm4-io-6_1/releases/tag/t3) but mouse/keyboard didn`t work on Rraspberry pi cm4 IO Board.
> 
> It seems like power isn’t being supplied to the USB port. 😦

If you use mirco-usb to connect the io board with the PC and then unplug it, can the recognition be restored?

**Comment by choihyunyong** [comment]
> > Hello
> > I found [github](https://github.com/rockchip-linux/rkbin) and build loader.
> > And flash [radxa-cm5-rpi-cm4-io-6_1_bookworm 1](https://github.com/radxa-build/radxa-cm5-rpi-cm4-io-6_1/releases/tag/t3) but mouse/keyboard didn`t work on Rraspberry pi cm4 IO Board.
> > It seems like power isn’t being supplied to the USB port. 😦
> 
> If you use mirco-usb to connect the io board with the PC and then unplug it, can the recognition be restored?

After unplugging the micro USB cable, the USB recognition worked! :)
Why that happend?

**Comment by Ken-Vamrs** [comment]
Then you can use “apt full-upgrade” to update your system. After the update, check whether the USB can be used normally. If not, you can wait for our next version of the image update, which will be fixed in the next version.
This is because there is a commit in the 6.1 kernel that will prevent OTG from automatically switching modes by detecting the USB ID.

**Comment by ginkage** [comment]
@Ken-Vamrs Could you please give a link to that commit, for the sake of completeness?

**Comment by RadxaYuntian** [comment]
Probably this: https://github.com/radxa/kernel/commit/ec8a9ad8bf5ddbe8ad7cba3d0deafbcba204092a

**Comment by ginkage** [comment]
@RadxaYuntian Thank you, this is really helpful.
